-- ai-portfolio project — schema for the Supabase split
-- Run this in the SQL editor of the ai-portfolio project ONLY.
-- Do NOT run it against the valerius project.
--
-- Creates the three tables moving off the shared backend:
--   reports     <- pm-agent
--   portfolio   <- demo-financial-webapp
--   valuations  <- demo-financial-webapp
--
-- Hardened as created rather than after the fact: RLS on, one anon SELECT policy
-- each, and no write policy at all. service_role bypasses RLS in Supabase, so the
-- server-side writers keep working while the anon key is read-only everywhere.
--
-- ids are GENERATED BY DEFAULT (not ALWAYS) so the copy step can insert explicit
-- ids if that ever becomes useful. Nothing foreign-keys these ids.

-- ---------------------------------------------------------------- reports ----
-- Read client-side by pm-agent-dashboard with the ANON key, hence anon_read.
-- Written by crew.py with the service key.
create table if not exists public.reports (
    id              bigint generated by default as identity primary key,
    created_at      timestamptz not null default now(),
    sprint_summary  text,
    risk_assessment text,
    final_report    text,
    jira_project    varchar
);

alter table public.reports enable row level security;

drop policy if exists anon_read on public.reports;
create policy anon_read on public.reports
    for select to anon using (true);

-- -------------------------------------------------------------- portfolio ----
-- No UNIQUE on ticker on purpose: the demo app dedups in code with a plain
-- insert plus delete-by-ticker. Adding a constraint here would break that path.
create table if not exists public.portfolio (
    id             bigint generated by default as identity primary key,
    created_at     timestamptz not null default now(),
    ticker         varchar,
    name           text,
    sector         text,
    classification varchar,
    primary_reason text
);

alter table public.portfolio enable row level security;

drop policy if exists anon_read on public.portfolio;
create policy anon_read on public.portfolio
    for select to anon using (true);

-- ------------------------------------------------------------- valuations ----
-- ticker IS unique here: the demo app upserts with on_conflict='ticker', which
-- requires a unique constraint to resolve against.
create table if not exists public.valuations (
    id             bigint generated by default as identity primary key,
    created_at     timestamptz not null default now(),
    ticker         varchar unique,
    classification varchar,
    report         text,
    recommendation varchar,
    summary        text
);

alter table public.valuations enable row level security;

drop policy if exists anon_read on public.valuations;
create policy anon_read on public.valuations
    for select to anon using (true);

-- ------------------------------------------------------------------ check ----
-- Expect three rows, rowsecurity = true on each.
select tablename, rowsecurity
from   pg_tables
where  schemaname = 'public'
  and  tablename in ('reports', 'portfolio', 'valuations')
order  by tablename;
